[workspace]
members = [
	"uefi-loader",
	"kernel",
	"bootinfo",
	"framebuffer",
	"fonts",
	"hal",
	"mem",
	"sync"
]

resolver = "2"

[package]
name = "nereus-os"
version = "0.1.0"
edition = "2021"

[dependencies]
